export const enum ActionTypes {
  OPEN_CHAT = "OPEN_CHAT",
  CREATE_MESSAGE = "CREATE_MESSAGE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  CONFIRM_DELETE_MESSAGE = "CONFIRM_DELETE_MESSAGE",
  RESET_VIEW_STATE = "RESET_VIEW_STATE",
}
